/*
 * @(#)IdAuto.java	2011-8-13
 *
 * Copyright (c) 2011. All Rights Reserved.
 *
 */

package com.github.javaclub.jorm.beans.id;

import com.github.javaclub.jorm.annotation.Entity;
import com.github.javaclub.jorm.annotation.Id;
import com.github.javaclub.jorm.annotation.PK;
import com.github.javaclub.jorm.annotation.constant.GenerationType;

/**
 * IdAuto
 *
 * @author <a href="mailto:gerald.chen.hz@gmail.com">Gerald Chen</a>
 * @version $Id: IdIdentityAutoGenerated.java 473 2011-09-25 14:44:05Z gerald.chen.hz@gmail.com $
 */
@Entity(table = "t_id_increment_auto_generated")
@PK("id")
public class IdIdentityAutoGenerated {

	@Id(GenerationType.IDENTITY)
	private int id;
	
	private String name;

	public IdIdentityAutoGenerated() {
		super();
	}

	public IdIdentityAutoGenerated(String name) {
		super();
		this.name = name;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "IdAuto [id=" + id + ", name=" + name + "]";
	}
}
